In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns=['day'], inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [4]:
# problem 1: 

# Outlook = sunny, temp=Hot, humidity=High, wind=Weak
# play or No play

In [6]:
# Solution 

# P(yes | Sunny, Hot, High, Weak)= P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | yes) * P(yes)
# P(No | Sunny, Hot, High, Weak)= P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

# Compare and decide using the maximum a posteriori rule

In [7]:
# Problem 2:

# outlook=Overcast, temp=Cool, humidity=Low, wind=Weak
# Play or No Play

In [8]:
# Solution

# P(Yes | Overcast, Cool, Low, Weak) = P(Overcast | Yes) * P(Cool | yes) * P(Low | Yes) * P(Weak | Yes) * P(Yes)
# P(No | Overcast, Cool, Low, Weak) = P(Overcast | No) * P(Cool | No) * P(Low | No) * P(Weak | No) * P(No)

In [9]:
# Training

## Lookup table (Dictionary) -> All the probabilities of the categories in each column

# Testing

In [10]:
# P(Yes)

# P(No)

In [11]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [12]:
prob_yes = 9/14
prob_no = 5/14

In [13]:
print(prob_yes)
print(prob_no)

0.6428571428571429
0.35714285714285715

In [14]:
# Outlook

pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [18]:
prob_overcast_no = 0
prob_rain_no = 2/5
prob_sunny_no = 3/5

prob_overcast_yes = 4/9
prob_rain_yes = 3/9
prob_sunny_yes = 2/9

In [19]:
# temp

pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [20]:
prob_cool_no = 1/5
prob_hot_no = 2/5
prob_mild_no = 2/5

prob_cool_yes = 3/9
prob_hot_yes = 2/9
prob_mild_yes = 4/9

In [21]:
# humidity

pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [22]:
prob_high_no = 4/5
prob_normal_no = 1/5

prob_high_yes = 3/9
prob_normal_yes = 6/9

In [23]:
# wind
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [25]:
prob_strong_no = 3/5
prob_weak_no = 2/5

prob_strong_yes = 3/9
prob_weak_yes = 6/9

In [26]:
# problem 1: 

# Outlook = sunny, temp=Hot, humidity=High, wind=Weak

PY = prob_yes* prob_sunny_yes * prob_hot_yes * prob_high_yes * prob_weak_yes

In [27]:
PY

0.007054673721340388

In [28]:
PN = prob_no* prob_sunny_no * prob_hot_no * prob_high_no * prob_weak_no

In [29]:
PN

0.02742857142857143

In [30]:
# probability of no is greater than yes therefore : No Play